title : Usman Anwar
show_downloads : True
theme: jekyll-theme-minimal
minima:
logo: "Profile.jpeg" 
markdown: kramdown
description: >- # this means to ignore newlines until "baseurl:"
profile_image: "assets/images/Profile.jpeg"
